import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-vercel-postgres'

// Idempotent BM (Bahasa Malaysia) column rollout for all CMS-driven globals.
// Adds the *_b_m sibling columns generated by Payload from fields suffixed `BM`,
// and creates the tables introduced for WhyCoolman page and Resources FAQs.
// Everything uses IF NOT EXISTS so the migration is safe on partially-migrated
// databases (dev with push:true) and fresh production.

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
    CREATE TABLE IF NOT EXISTS "why_coolman_page" (
      "id" serial PRIMARY KEY NOT NULL,
      "hero_eyebrow" varchar DEFAULT 'Why Coolman',
      "hero_eyebrow_b_m" varchar DEFAULT 'Kenapa Coolman',
      "hero_title" varchar DEFAULT 'The Coolman Advantage',
      "hero_title_b_m" varchar DEFAULT 'Kelebihan Coolman',
      "hero_lede" varchar,
      "hero_lede_b_m" varchar,
      "stats_section_title" varchar DEFAULT 'Trusted by Professionals',
      "stats_section_title_b_m" varchar DEFAULT 'Dipercayai Oleh Profesional',
      "stats_section_subtitle" varchar,
      "stats_section_subtitle_b_m" varchar,
      "testimonials_section_eyebrow" varchar DEFAULT 'Testimonials',
      "testimonials_section_eyebrow_b_m" varchar DEFAULT 'Testimoni',
      "testimonials_section_title" varchar DEFAULT 'What Our Partners Say',
      "testimonials_section_title_b_m" varchar DEFAULT 'Apa Kata Rakan Kongsi Kami',
      "cta_title" varchar DEFAULT 'Ready to Experience the Difference?',
      "cta_title_b_m" varchar DEFAULT 'Sedia Merasai Perbezaannya?',
      "cta_body" varchar,
      "cta_body_b_m" varchar,
      "cta_primary_label" varchar DEFAULT 'Become a Partner',
      "cta_primary_label_b_m" varchar DEFAULT 'Jadi Rakan Kongsi',
      "cta_primary_href" varchar DEFAULT '/auth/register',
      "cta_secondary_label" varchar DEFAULT 'Contact Sales',
      "cta_secondary_label_b_m" varchar DEFAULT 'Hubungi Jualan',
      "cta_secondary_href" varchar DEFAULT '/contact',
      "updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
      "created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
    );

    CREATE TABLE IF NOT EXISTS "why_coolman_page_advantages" (
      "_order" integer NOT NULL,
      "_parent_id" integer NOT NULL,
      "id" varchar PRIMARY KEY NOT NULL,
      "icon_key" varchar DEFAULT 'zap' NOT NULL,
      "title" varchar NOT NULL,
      "title_b_m" varchar,
      "body" varchar NOT NULL,
      "body_b_m" varchar
    );

    CREATE TABLE IF NOT EXISTS "why_coolman_page_stats" (
      "_order" integer NOT NULL,
      "_parent_id" integer NOT NULL,
      "id" varchar PRIMARY KEY NOT NULL,
      "value" varchar NOT NULL,
      "label" varchar NOT NULL,
      "label_b_m" varchar
    );

    CREATE TABLE IF NOT EXISTS "why_coolman_page_testimonials" (
      "_order" integer NOT NULL,
      "_parent_id" integer NOT NULL,
      "id" varchar PRIMARY KEY NOT NULL,
      "quote" varchar NOT NULL,
      "quote_b_m" varchar,
      "author" varchar NOT NULL,
      "role" varchar NOT NULL,
      "role_b_m" varchar
    );

    CREATE TABLE IF NOT EXISTS "resources_page_faqs" (
      "_order" integer NOT NULL,
      "_parent_id" integer NOT NULL,
      "id" varchar PRIMARY KEY NOT NULL,
      "question" varchar NOT NULL,
      "question_b_m" varchar,
      "answer" varchar NOT NULL,
      "answer_b_m" varchar
    );

    DO $$ BEGIN
      ALTER TABLE "why_coolman_page_advantages" ADD CONSTRAINT "why_coolman_page_advantages_parent_id_fk"
        FOREIGN KEY ("_parent_id") REFERENCES "public"."why_coolman_page"("id") ON DELETE cascade ON UPDATE no action;
    EXCEPTION WHEN duplicate_object THEN NULL; END $$;

    DO $$ BEGIN
      ALTER TABLE "why_coolman_page_stats" ADD CONSTRAINT "why_coolman_page_stats_parent_id_fk"
        FOREIGN KEY ("_parent_id") REFERENCES "public"."why_coolman_page"("id") ON DELETE cascade ON UPDATE no action;
    EXCEPTION WHEN duplicate_object THEN NULL; END $$;

    DO $$ BEGIN
      ALTER TABLE "why_coolman_page_testimonials" ADD CONSTRAINT "why_coolman_page_testimonials_parent_id_fk"
        FOREIGN KEY ("_parent_id") REFERENCES "public"."why_coolman_page"("id") ON DELETE cascade ON UPDATE no action;
    EXCEPTION WHEN duplicate_object THEN NULL; END $$;

    DO $$ BEGIN
      ALTER TABLE "resources_page_faqs" ADD CONSTRAINT "resources_page_faqs_parent_id_fk"
        FOREIGN KEY ("_parent_id") REFERENCES "public"."resources_page"("id") ON DELETE cascade ON UPDATE no action;
    EXCEPTION WHEN duplicate_object THEN NULL; END $$;

    CREATE INDEX IF NOT EXISTS "why_coolman_page_advantages_order_idx" ON "why_coolman_page_advantages" USING btree ("_order");
    CREATE INDEX IF NOT EXISTS "why_coolman_page_advantages_parent_id_idx" ON "why_coolman_page_advantages" USING btree ("_parent_id");
    CREATE INDEX IF NOT EXISTS "why_coolman_page_stats_order_idx" ON "why_coolman_page_stats" USING btree ("_order");
    CREATE INDEX IF NOT EXISTS "why_coolman_page_stats_parent_id_idx" ON "why_coolman_page_stats" USING btree ("_parent_id");
    CREATE INDEX IF NOT EXISTS "why_coolman_page_testimonials_order_idx" ON "why_coolman_page_testimonials" USING btree ("_order");
    CREATE INDEX IF NOT EXISTS "why_coolman_page_testimonials_parent_id_idx" ON "why_coolman_page_testimonials" USING btree ("_parent_id");
    CREATE INDEX IF NOT EXISTS "resources_page_faqs_order_idx" ON "resources_page_faqs" USING btree ("_order");
    CREATE INDEX IF NOT EXISTS "resources_page_faqs_parent_id_idx" ON "resources_page_faqs" USING btree ("_parent_id");

    -- home_page (top-level group fields are flattened with group_field naming)
    ALTER TABLE "home_page_stats" ADD COLUMN IF NOT EXISTS "label_b_m" varchar;
    ALTER TABLE "home_page_features" ADD COLUMN IF NOT EXISTS "title_b_m" varchar;
    ALTER TABLE "home_page_features" ADD COLUMN IF NOT EXISTS "description_b_m" varchar;
    ALTER TABLE "home_page_features" ADD COLUMN IF NOT EXISTS "stat_label_b_m" varchar;
    ALTER TABLE "home_page_application_list" ADD COLUMN IF NOT EXISTS "label_b_m" varchar;
    ALTER TABLE "home_page" ADD COLUMN IF NOT EXISTS "hero_badge_b_m" varchar;
    ALTER TABLE "home_page" ADD COLUMN IF NOT EXISTS "hero_headline_line1_b_m" varchar;
    ALTER TABLE "home_page" ADD COLUMN IF NOT EXISTS "hero_headline_line2_b_m" varchar;
    ALTER TABLE "home_page" ADD COLUMN IF NOT EXISTS "hero_headline_line3_b_m" varchar;
    ALTER TABLE "home_page" ADD COLUMN IF NOT EXISTS "hero_subheadline_b_m" varchar;
    ALTER TABLE "home_page" ADD COLUMN IF NOT EXISTS "hero_primary_cta_label_b_m" varchar;
    ALTER TABLE "home_page" ADD COLUMN IF NOT EXISTS "hero_secondary_cta_label_b_m" varchar;
    ALTER TABLE "home_page" ADD COLUMN IF NOT EXISTS "cta_section_headline_b_m" varchar;
    ALTER TABLE "home_page" ADD COLUMN IF NOT EXISTS "cta_section_subheadline_b_m" varchar;
    ALTER TABLE "home_page" ADD COLUMN IF NOT EXISTS "cta_section_primary_cta_label_b_m" varchar;
    ALTER TABLE "home_page" ADD COLUMN IF NOT EXISTS "cta_section_secondary_cta_label_b_m" varchar;

    -- applications_page
    ALTER TABLE "applications_page" ADD COLUMN IF NOT EXISTS "hero_title_b_m" varchar;
    ALTER TABLE "applications_page" ADD COLUMN IF NOT EXISTS "hero_subtitle_b_m" varchar;
    ALTER TABLE "applications_page_sections" ADD COLUMN IF NOT EXISTS "title_b_m" varchar;
    ALTER TABLE "applications_page_sections" ADD COLUMN IF NOT EXISTS "description_b_m" varchar;

    -- resources_page
    ALTER TABLE "resources_page" ADD COLUMN IF NOT EXISTS "hero_title_b_m" varchar;
    ALTER TABLE "resources_page" ADD COLUMN IF NOT EXISTS "hero_subtitle_b_m" varchar;
    ALTER TABLE "resources_page_downloads" ADD COLUMN IF NOT EXISTS "title_b_m" varchar;
    ALTER TABLE "resources_page_downloads" ADD COLUMN IF NOT EXISTS "description_b_m" varchar;
    ALTER TABLE "resources_page_videos" ADD COLUMN IF NOT EXISTS "title_b_m" varchar;
    ALTER TABLE "resources_page_videos" ADD COLUMN IF NOT EXISTS "description_b_m" varchar;

    -- contact_page
    ALTER TABLE "contact_page" ADD COLUMN IF NOT EXISTS "hero_title_b_m" varchar;
    ALTER TABLE "contact_page" ADD COLUMN IF NOT EXISTS "hero_subtitle_b_m" varchar;
    ALTER TABLE "contact_page" ADD COLUMN IF NOT EXISTS "address_b_m" varchar;
    ALTER TABLE "contact_page" ADD COLUMN IF NOT EXISTS "response_time" varchar DEFAULT '< 4 hours';

    -- shibuya_page
    ALTER TABLE "shibuya_page" ADD COLUMN IF NOT EXISTS "hero_badge_b_m" varchar;
    ALTER TABLE "shibuya_page" ADD COLUMN IF NOT EXISTS "hero_headline_line1_b_m" varchar;
    ALTER TABLE "shibuya_page" ADD COLUMN IF NOT EXISTS "hero_headline_line2_b_m" varchar;
    ALTER TABLE "shibuya_page" ADD COLUMN IF NOT EXISTS "hero_subheadline_b_m" varchar;
    ALTER TABLE "shibuya_page" ADD COLUMN IF NOT EXISTS "heritage_statement_b_m" varchar;
    ALTER TABLE "shibuya_page" ADD COLUMN IF NOT EXISTS "craftsmanship_section_label_b_m" varchar;
    ALTER TABLE "shibuya_page" ADD COLUMN IF NOT EXISTS "craftsmanship_title_b_m" varchar;
    ALTER TABLE "shibuya_page" ADD COLUMN IF NOT EXISTS "craftsmanship_body_b_m" varchar;
    ALTER TABLE "shibuya_page" ADD COLUMN IF NOT EXISTS "in_action_title_b_m" varchar;
    ALTER TABLE "shibuya_page" ADD COLUMN IF NOT EXISTS "in_action_body_b_m" varchar;
    ALTER TABLE "shibuya_page" ADD COLUMN IF NOT EXISTS "support_title_b_m" varchar;
    ALTER TABLE "shibuya_page" ADD COLUMN IF NOT EXISTS "cta_headline_b_m" varchar;
    ALTER TABLE "shibuya_page" ADD COLUMN IF NOT EXISTS "cta_subheadline_b_m" varchar;
    ALTER TABLE "shibuya_page" ADD COLUMN IF NOT EXISTS "cta_primary_cta_label_b_m" varchar;
    ALTER TABLE "shibuya_page" ADD COLUMN IF NOT EXISTS "cta_secondary_cta_label_b_m" varchar;
    ALTER TABLE "shibuya_page_craftsmanship_points" ADD COLUMN IF NOT EXISTS "title_b_m" varchar;
    ALTER TABLE "shibuya_page_craftsmanship_points" ADD COLUMN IF NOT EXISTS "description_b_m" varchar;
    ALTER TABLE "shibuya_page_machines" ADD COLUMN IF NOT EXISTS "tagline_b_m" varchar;
    ALTER TABLE "shibuya_page_machines" ADD COLUMN IF NOT EXISTS "description_b_m" varchar;
    ALTER TABLE "shibuya_page_machines_features" ADD COLUMN IF NOT EXISTS "feature_b_m" varchar;
    ALTER TABLE "shibuya_page_support_items" ADD COLUMN IF NOT EXISTS "title_b_m" varchar;
    ALTER TABLE "shibuya_page_support_items" ADD COLUMN IF NOT EXISTS "description_b_m" varchar;
  `)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
    ALTER TABLE "home_page_stats" DROP COLUMN IF EXISTS "label_b_m";
    ALTER TABLE "home_page_features" DROP COLUMN IF EXISTS "title_b_m";
    ALTER TABLE "home_page_features" DROP COLUMN IF EXISTS "description_b_m";
    ALTER TABLE "home_page_features" DROP COLUMN IF EXISTS "stat_label_b_m";
    ALTER TABLE "home_page_application_list" DROP COLUMN IF EXISTS "label_b_m";
    ALTER TABLE "home_page" DROP COLUMN IF EXISTS "hero_badge_b_m";
    ALTER TABLE "home_page" DROP COLUMN IF EXISTS "hero_headline_line1_b_m";
    ALTER TABLE "home_page" DROP COLUMN IF EXISTS "hero_headline_line2_b_m";
    ALTER TABLE "home_page" DROP COLUMN IF EXISTS "hero_headline_line3_b_m";
    ALTER TABLE "home_page" DROP COLUMN IF EXISTS "hero_subheadline_b_m";
    ALTER TABLE "home_page" DROP COLUMN IF EXISTS "hero_primary_cta_label_b_m";
    ALTER TABLE "home_page" DROP COLUMN IF EXISTS "hero_secondary_cta_label_b_m";
    ALTER TABLE "home_page" DROP COLUMN IF EXISTS "cta_section_headline_b_m";
    ALTER TABLE "home_page" DROP COLUMN IF EXISTS "cta_section_subheadline_b_m";
    ALTER TABLE "home_page" DROP COLUMN IF EXISTS "cta_section_primary_cta_label_b_m";
    ALTER TABLE "home_page" DROP COLUMN IF EXISTS "cta_section_secondary_cta_label_b_m";
    ALTER TABLE "applications_page" DROP COLUMN IF EXISTS "hero_title_b_m";
    ALTER TABLE "applications_page" DROP COLUMN IF EXISTS "hero_subtitle_b_m";
    ALTER TABLE "applications_page_sections" DROP COLUMN IF EXISTS "title_b_m";
    ALTER TABLE "applications_page_sections" DROP COLUMN IF EXISTS "description_b_m";
    ALTER TABLE "resources_page" DROP COLUMN IF EXISTS "hero_title_b_m";
    ALTER TABLE "resources_page" DROP COLUMN IF EXISTS "hero_subtitle_b_m";
    ALTER TABLE "resources_page_downloads" DROP COLUMN IF EXISTS "title_b_m";
    ALTER TABLE "resources_page_downloads" DROP COLUMN IF EXISTS "description_b_m";
    ALTER TABLE "resources_page_videos" DROP COLUMN IF EXISTS "title_b_m";
    ALTER TABLE "resources_page_videos" DROP COLUMN IF EXISTS "description_b_m";
    ALTER TABLE "contact_page" DROP COLUMN IF EXISTS "hero_title_b_m";
    ALTER TABLE "contact_page" DROP COLUMN IF EXISTS "hero_subtitle_b_m";
    ALTER TABLE "contact_page" DROP COLUMN IF EXISTS "address_b_m";
    ALTER TABLE "contact_page" DROP COLUMN IF EXISTS "response_time";
    ALTER TABLE "shibuya_page_craftsmanship_points" DROP COLUMN IF EXISTS "title_b_m";
    ALTER TABLE "shibuya_page_craftsmanship_points" DROP COLUMN IF EXISTS "description_b_m";
    ALTER TABLE "shibuya_page_machines_features" DROP COLUMN IF EXISTS "feature_b_m";
    ALTER TABLE "shibuya_page_machines" DROP COLUMN IF EXISTS "tagline_b_m";
    ALTER TABLE "shibuya_page_machines" DROP COLUMN IF EXISTS "description_b_m";
    ALTER TABLE "shibuya_page_support_items" DROP COLUMN IF EXISTS "title_b_m";
    ALTER TABLE "shibuya_page_support_items" DROP COLUMN IF EXISTS "description_b_m";
    ALTER TABLE "shibuya_page" DROP COLUMN IF EXISTS "hero_badge_b_m";
    ALTER TABLE "shibuya_page" DROP COLUMN IF EXISTS "hero_headline_line1_b_m";
    ALTER TABLE "shibuya_page" DROP COLUMN IF EXISTS "hero_headline_line2_b_m";
    ALTER TABLE "shibuya_page" DROP COLUMN IF EXISTS "hero_subheadline_b_m";
    ALTER TABLE "shibuya_page" DROP COLUMN IF EXISTS "heritage_statement_b_m";
    ALTER TABLE "shibuya_page" DROP COLUMN IF EXISTS "craftsmanship_section_label_b_m";
    ALTER TABLE "shibuya_page" DROP COLUMN IF EXISTS "craftsmanship_title_b_m";
    ALTER TABLE "shibuya_page" DROP COLUMN IF EXISTS "craftsmanship_body_b_m";
    ALTER TABLE "shibuya_page" DROP COLUMN IF EXISTS "in_action_title_b_m";
    ALTER TABLE "shibuya_page" DROP COLUMN IF EXISTS "in_action_body_b_m";
    ALTER TABLE "shibuya_page" DROP COLUMN IF EXISTS "support_title_b_m";
    ALTER TABLE "shibuya_page" DROP COLUMN IF EXISTS "cta_headline_b_m";
    ALTER TABLE "shibuya_page" DROP COLUMN IF EXISTS "cta_subheadline_b_m";
    ALTER TABLE "shibuya_page" DROP COLUMN IF EXISTS "cta_primary_cta_label_b_m";
    ALTER TABLE "shibuya_page" DROP COLUMN IF EXISTS "cta_secondary_cta_label_b_m";
    DROP TABLE IF EXISTS "resources_page_faqs" CASCADE;
    DROP TABLE IF EXISTS "why_coolman_page_advantages" CASCADE;
    DROP TABLE IF EXISTS "why_coolman_page_stats" CASCADE;
    DROP TABLE IF EXISTS "why_coolman_page_testimonials" CASCADE;
    DROP TABLE IF EXISTS "why_coolman_page" CASCADE;
  `)
}
